spring:

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8
    username: root
    password: root


  #spring.mvc.static-path-pattern=/static/** 加载静态资源
  mvc:
    static-path-pattern: /static/**


  #freemarker静态资源配置
  freemarker:
    #设置ftl文件路径
    template-loader-path: classpath:/templates
    #关闭缓存，及时更新，上线需要改成true
    cache: false
    #编码格式
    charset: UTF-8
    #识别文件类型
    content-type: text/html
    #freemarker后缀
    suffix: .ftl
    #是否检查templates路径是否存在
    check-template-location: true


  #thymeleaf静态资源配配置
  thymeleaf:
    #文件路径
    prefix: classpath:/templates/
    #后缀
    suffix: .html
    #模式
    mode: HTML5
    #编码
    encoding: UTF-8
    #识别文件类型
    #关闭缓存，及时更新，上线需要改成true
    cache: false
    servlet:
      content-type: text/html


myprops:
  className: com.afuo.learntools.pojo.User
  methodName: eat
  userIdList:
    - 1001
    - 1002
  userMap:
    id: 1003
    name: zhangsan
  userList:
    - id: 1004
      name: "李四"
    - id: 1005
      name: "王五"


#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

